classprac/classprac/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from first_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_app.urls')),
]

classprac/first_app/urls.py
from django.conf.urls import url
from django.urls import path
from first_app import views

app_name = 'first_app'

urlpatterns = [
    path('', views.indexView2.as_view(), name='index'),
    path('musician_details/<pk>/', views.FighterDetail.as_view(), name='fighter_details'),
    path('add_fighters/', views.AddFighter.as_view(), name='add_fighters'),
    path('update_fighters/<pk>/', views.UpdateFighter.as_view(), name='update_fighters'),
    path('delete_fighters/<pk>/', views.DeleteFighter.as_view(), name='delete_fighter'),
]

classprac/first_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Fighter(models.Model):
    # id = models.AutoField(primary_key = True) automatically created by django
    first_name = models.CharField(max_length = 30)
    last_name  = models.CharField(max_length = 30)
    style = models.CharField(max_length = 30)

    def __str__(self):
        return self.first_name + " " + self.last_name
        return self.instrument
    def get_absolute_url(self):
        return reverse("first_app:fighter_details", kwargs={'pk':self.pk})

class Achievements(models.Model):
    # id = models.AutoField(primary_key = True) automatically created by django
    fighter = models.ForeignKey(Fighter, on_delete= models.CASCADE, related_name='fighter_list')
    name  = models.CharField(max_length = 30)


    def __str__(self):
        return self.name

classprac/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from first_app import models
from django.urls import reverse_lazy
# def index_test(request):
#     dic={}
#     return HttpResponse('Hello World!')

class indexView(TemplateView):
    template_name = 'first_app/index1.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['s1'] = 'sameple text 1'
        context['s2'] = 'sample text 2'
        return context

class indexView2(ListView):
    context_object_name = 'Fighter_list'
    model = models.Fighter
    template_name = 'first_app/index1.html'

class FighterDetail(DetailView):
    context_object_name = 'fighter'
    model = models.Fighter
    template_name = 'first_app/fighter_details.html'

class AddFighter(CreateView):
    fields = ('first_name','last_name','style')
    model = models.Fighter
    template_name = 'first_app/fighter_form.html'
class UpdateFighter(UpdateView):
    fields = ('first_name','last_name','style')
    model = models.Fighter
    template_name = 'first_app/update_fighter.html'

class DeleteFighter(DeleteView):
    context_object_name = 'fighter'
    model = models.Fighter
    success_url = reverse_lazy("first_app:index")
    template_name = 'first_app/delete_fighter.html'

classprac/first_app/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="utf-8">
    <title>{{title}}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'first_app:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active"  href="{% url 'first_app:add_fighters' %}">Add Fighters</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  {% block body_block %}

  {% endblock %}
</div>

  </body>
</html>

classprac/first_app/templates/first_app/delete_fighter.html
{% extends 'first_app/base.html' %}
{% block body_block %}

<h3>Delete {{fighter.first_name}} {{fighter.last_name}}?</h3>
<form  method="POST">
{{form.as_p}}
{% csrf_token  %}
<input type="Submit" name="Submit" value="Delete" class="btn btn-danger btn-sm">
<br>
<a href="{% url 'first_app:fighter_details' pk=fighter.pk %}" class="btn btn-info btn-sm">Cancel</a>
</form>
{% endblock %}

classprac/first_app/templates/first_app/fighter_details.html
{% extends 'first_app/base.html' %}
{% block body_block %}

<h3>Fighter Detail</h3>

<p>{{fighter.first_name}} {{fighter.last_name}}</p>
<p>{{fighter.style}}</p>
<h3>Achievements</h3>
{% for ach in fighter.fighter_list.all %}
<ul>
  <li>{{ach.name}}</li>
</ul>
{% endfor %}
<a href="{% url 'first_app:update_fighters' pk=fighter.pk %}" class="btn btn-warning btn-sm">Update</a>
<br>
<a href="{% url 'first_app:delete_fighter' pk=fighter.pk %}" class="btn btn-danger btn-sm">Delete</a>
{% endblock %}

classprac/first_app/templates/first_app/fighter_form.html
{% extends 'first_app/base.html' %}
{% block body_block %}

<h3>Add New Fighters</h3>
<form  method="POST">

{{form.as_p}}
{% csrf_token  %}

<input type="Submit" name="Submit" value="Add" class="btn btn-primary btn-sm">
</form>

{% endblock %}

classprac/first_app/templates/first_app/index1.html
{% extends 'first_app/base.html' %}
{% block body_block %}
<ul>
{% for fighter in Fighter_list %}
<li><a href="{% url 'first_app:fighter_details' pk=fighter.pk %}">{{fighter.first_name}} {{fighter.last_name}}</a></li>
{% endfor %}
</ul>
{% endblock %}

classprac/first_app/templates/first_app/update_fighter.html
{% extends 'first_app/base.html' %}
{% block body_block %}

<h3>Update Fighters</h3>
<form  method="POST">

{{form.as_p}}
{% csrf_token  %}

<input type="Submit" name="Submit" value="Add" class="btn btn-primary btn-sm">
</form>

{% endblock %}